### ISSUE TITLE
Code release timeline

### ISSUE THREAD

**Issue by laubravo** [ttxskk/AiOS#1]
Hi,

Great paper! Do you have an estimate on when you'll release the training code and pretrained weights?

**Comment by fabienbaradel** [comment]
@laubravo do yo know where is the paper? I cannot find it on arXiv.

**Comment by ttxskk** [comment]
Hi @laubravo,

Thank you for your interest in AiOS. We expect to release our code and checkpoint before the end of April.

Please stay tuned for updates, and thank you again for your attention to AiOS.

**Comment by ttxskk** [comment]
The code and model have been released. If you have any other questions, pls reopen it.
