### ISSUE TITLE
Global pose for the bones

### ISSUE THREAD

**Issue by iamthephd** [ttxskk/AiOS#13]
I have a query regarding the global pose. How can we get the global poses for each bone, similar to what is done in [WHAM](https://github.com/yohanshin/WHAM/blob/2b54f7797391c94876848b905ed875b154c4a295/demo.py#L157).

**Comment by ttxskk** [comment]
Hi @iamthephd ,

Sorry for the delayed response. AiOS primarily runs in camera space, which means it doesn't provide the correct global pose. If you need the pose in world space, I recommend checking out [WHAC](https://github.com/wqyin/WHAC). As far as I know, the code will be made public soon.

**Comment by ttxskk** [comment]
Closed. Please feel free to reopen it if this doesn't resolve your issue.
