### ISSUE TITLE
Question about Computational cost and speed.

### ISSUE THREAD

**Issue by chojinie** [ttxskk/AiOS#3]
Hi, @ttxskk 
Thanks for share nice work.

I skim the paper quickly, and didn't catch about computational cost and speed.

when i look the overall framework's workflow, In my opinion, The process is not shorten compare with OSX(CVPR 2023)

So i'm very curious about your work achieve more faster and lighter than before works. 

Sincerely,

**Comment by ttxskk** [comment]
Hi @chojinie,

Thank you for your interest and your question. Actually, AiOS is not designed for lightweight models. Its primary aim is to demonstrate that a DETR-style one-stage pipeline can be effectively implemented for EHPS to achieve SoTA performance on well-known benchmarks like AGORA and BEDLAM.

Regarding the computational cost and speed of AiOS, we haven’t conducted specific measurements. However, we guess that the Native AiOS would likely have a computational cost comparable to [DeformableDETR](https://github.com/fundamentalvision/Deformable-DETR?tab=readme-ov-file#main-results), while the full AiOS version should be similar to [ED-Pose](https://github.com/IDEA-Research/ED-Pose).

Additionally, unlike OSX, which depends on an off-the-shelf detection model to detect and crop humans from images, AiOS simplifies the process by automatically perceiving the human position from the image, which means AiOS doesn't require an off-the-shelf detection model.

Hope this can resolve your question.

**Comment by ttxskk** [comment]
Closed. Please feel free to reopen it if you have further questions.
