### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by Marlod390** [ttxskk/AiOS#8]
Dear authors,

 thank you for your great work. But i encountered some problem in installation. 

The first is in your installation instruction, there is no requirement.txt

The second is `Traceback (most recent call last):
  File "main.py", line 14, in <module>
Traceback (most recent call last):
      File "main.py", line 14, in <module>
from detrsmpl.data.datasets import build_dataloader
ModuleNotFoundError: No module named 'detrsmpl.data'
    from detrsmpl.data.datasets import build_dataloader
ModuleNotFoundError: No module named 'detrsmpl.data'` when running official demo

**Comment by WYJSJTU** [comment]
It should be fixed now with the latest commit.

**Comment by clover978** [comment]
@WYJSJTU `requirement.txt` is still missing.

**Comment by WYJSJTU** [comment]
The `requirement.txt` has been added with commit [b33fc81](https://github.com/ttxskk/AiOS/commit/b33fc81dea27e99a088001c759455a2f3a4115ba).
