### ISSUE TITLE
Error running demo

### ISSUE THREAD

**Issue by Marlod390** [ttxskk/AiOS#9]
Dear Authors, 

thanks for your great work. But i encountered following error when running official demo:

`(/mnt/qb/work/ponsmoll/pba178/.conda/aios) [pba178@galvani-cn219 AiOS]$ sh scripts/inference.sh short_video demo

/mnt/qb/work/ponsmoll/pba178/.conda/aios/lib/python3.8/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
usage: DETR training and evaluation script [-h] --config_file CONFIG_FILE [--options OPTIONS [OPTIONS ...]] [--output_dir OUTPUT_DIR] [--device DEVICE] [--seed SEED] [--resume RESUME]
                                           [--pretrain_model_path PRETRAIN_MODEL_PATH] [--finetune_ignore FINETUNE_IGNORE [FINETUNE_IGNORE ...]] [--start_epoch N] [--eval] [--num_workers NUM_WORKERS]
                                           [--test] [--debug] [--find_unused_params] [--save_log] [--to_vid] [--inference] [--rank RANK] [--local_rank LOCAL_RANK] [--amp]
                                           [--inference_input INFERENCE_INPUT]
DETR training and evaluation script: error: unrecognized arguments: --local-rank=0
usage: DETR training and evaluation script [-h] --config_file CONFIG_FILE [--options OPTIONS [OPTIONS ...]] [--output_dir OUTPUT_DIR] [--device DEVICE] [--seed SEED] [--resume RESUME]
                                           [--pretrain_model_path PRETRAIN_MODEL_PATH] [--finetune_ignore FINETUNE_IGNORE [FINETUNE_IGNORE ...]] [--start_epoch N] [--eval] [--num_workers NUM_WORKERS]
                                           [--test] [--debug] [--find_unused_params] [--save_log] [--to_vid] [--inference] [--rank RANK] [--local_rank LOCAL_RANK] [--amp]
                                           [--inference_input INFERENCE_INPUT]
DETR training and evaluation script: error: unrecognized arguments: --local-rank=1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 3022941) of binary: /mnt/qb/work/ponsmoll/pba178/.conda/aios/bin/python
Traceback (most recent call last):
  File "/mnt/qb/work/ponsmoll/pba178/.conda/aios/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/qb/work/ponsmoll/pba178/.conda/aios/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/qb/work/ponsmoll/pba178/.conda/aios/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/mnt/qb/work/ponsmoll/pba178/.conda/aios/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/mnt/qb/work/ponsmoll/pba178/.conda/aios/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/mnt/qb/work/ponsmoll/pba178/.conda/aios/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/mnt/qb/work/ponsmoll/pba178/.conda/aios/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/qb/work/ponsmoll/pba178/.conda/aios/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-05-21_23:12:25
  host      : galvani-cn219
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 3022942)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-21_23:12:25
  host      : galvani-cn219
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 3022941)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
`

I have downloaded the checkpoint and SMPL content and placed them in correct path, but this error still occurs. I would like to know if you have any solution for this problem

**Comment by ttxskk** [comment]
@WYJSJTU, could you help to check this issue?
